/* The following code was generated by JFlex 1.4.3 on 18/10/20 20:12 */

package principal;
import static principal.Tokens.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 18/10/20 20:12 from the specification file
 * <tt>C:/Users/elmer/Desktop/Proyecto-Compiladores/src/principal/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\54\2\0\1\3\22\0\1\53\1\52\1\0\1\55"+
    "\1\55\1\42\1\55\1\0\1\44\1\45\1\40\1\36\1\50\1\37"+
    "\1\55\1\41\12\2\1\55\1\51\1\46\1\35\1\47\1\55\1\0"+
    "\1\30\1\33\2\1\1\31\14\1\1\32\10\1\3\0\1\43\1\1"+
    "\1\0\1\12\1\15\1\11\1\13\1\4\1\21\1\26\1\23\1\17"+
    "\2\1\1\14\1\22\1\5\1\10\1\24\1\1\1\7\1\16\1\6"+
    "\1\25\1\20\1\1\1\27\1\1\1\34\1\55\1\0\1\55\43\0"+
    "\1\55\22\0\1\55\12\0\1\55\uff40\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\1\2\1\3\1\1\1\4\20\3\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\4\1\20\2\1\7\3\1\21\11\3\1\21"+
    "\10\3\1\22\1\23\1\24\1\1\1\25\1\26\33\3"+
    "\2\1\1\0\1\25\31\3\1\0\1\27\24\3\1\27"+
    "\4\3\1\21\26\3";

  private static int [] zzUnpackAction() {
    int [] result = new int[174];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\56\0\134\0\212\0\270\0\346\0\u0114\0\u0142"+
    "\0\u0170\0\u019e\0\u01cc\0\u01fa\0\u0228\0\u0256\0\u0284\0\u02b2"+
    "\0\u02e0\0\u030e\0\u033c\0\u036a\0\u0398\0\u03c6\0\u03f4\0\u0422"+
    "\0\212\0\u0450\0\212\0\56\0\212\0\212\0\212\0\212"+
    "\0\u047e\0\212\0\u04ac\0\u04da\0\u0508\0\u0536\0\u0564\0\u0592"+
    "\0\u05c0\0\u05ee\0\u061c\0\134\0\u064a\0\u0678\0\u06a6\0\u06d4"+
    "\0\u0702\0\u0730\0\u075e\0\u078c\0\u07ba\0\u07ba\0\u07e8\0\u0816"+
    "\0\u0844\0\u0872\0\u08a0\0\u08ce\0\u08fc\0\u092a\0\56\0\212"+
    "\0\212\0\u0958\0\u0986\0\56\0\u09b4\0\u09e2\0\u0a10\0\u0a3e"+
    "\0\u0a6c\0\u0a9a\0\u0ac8\0\u0af6\0\u0b24\0\u0b52\0\u0b80\0\u0bae"+
    "\0\u0bdc\0\u0c0a\0\u0c38\0\u0c66\0\u0c94\0\u0cc2\0\u0cf0\0\u0d1e"+
    "\0\u0d4c\0\u0d7a\0\u0da8\0\u0dd6\0\u0e04\0\u0e32\0\u0e60\0\u0e8e"+
    "\0\u0ebc\0\u0eea\0\u0f18\0\u0f46\0\u0f74\0\u0fa2\0\u0fd0\0\u0ffe"+
    "\0\u102c\0\u105a\0\u1088\0\u10b6\0\u10e4\0\u1112\0\u1140\0\u116e"+
    "\0\u119c\0\u11ca\0\u11f8\0\u1226\0\u1254\0\u1282\0\u12b0\0\u12de"+
    "\0\u130c\0\u133a\0\u1368\0\u1396\0\u13c4\0\212\0\u13f2\0\u1420"+
    "\0\u144e\0\u147c\0\u14aa\0\u14d8\0\u1506\0\u1534\0\u1562\0\u1590"+
    "\0\u15be\0\u15ec\0\u161a\0\u1648\0\u1676\0\u16a4\0\u16d2\0\u1700"+
    "\0\u172e\0\u175c\0\56\0\u178a\0\u17b8\0\u17e6\0\u1814\0\u1842"+
    "\0\u1870\0\u189e\0\u18cc\0\u18fa\0\u1928\0\u1956\0\u1984\0\u19b2"+
    "\0\u19e0\0\u1a0e\0\u1a3c\0\u1a6a\0\u1a98\0\u1ac6\0\u1af4\0\u1b22"+
    "\0\u1b50\0\u1b7e\0\u1bac\0\u1bda\0\u1c08\0\u1c36";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[174];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\3\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\10\3\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\1\42\1\43\2\5\1\4\57\0\2\3"+
    "\1\0\31\3\22\0\1\44\1\4\1\0\31\44\1\0"+
    "\5\4\1\0\7\4\2\0\1\4\3\0\1\5\44\0"+
    "\1\5\2\0\2\5\2\0\2\3\1\0\1\3\1\45"+
    "\6\3\1\46\1\3\1\47\10\3\1\50\5\3\22\0"+
    "\2\3\1\0\6\3\1\51\22\3\22\0\2\3\1\0"+
    "\1\52\5\3\1\53\22\3\22\0\2\3\1\0\3\3"+
    "\1\54\25\3\22\0\2\3\1\0\4\3\1\55\1\3"+
    "\1\56\1\3\1\57\20\3\22\0\2\3\1\0\1\3"+
    "\1\60\27\3\22\0\2\3\1\0\1\61\30\3\22\0"+
    "\2\3\1\0\1\62\3\3\1\63\24\3\22\0\2\3"+
    "\1\0\4\3\1\64\24\3\22\0\2\3\1\0\1\65"+
    "\12\3\1\66\15\3\22\0\2\3\1\0\1\3\1\67"+
    "\27\3\22\0\2\3\1\0\1\70\30\3\22\0\2\3"+
    "\1\0\6\3\1\71\22\3\22\0\2\3\1\0\1\72"+
    "\12\3\1\73\15\3\22\0\2\3\1\0\6\3\1\74"+
    "\22\3\22\0\2\3\1\0\3\3\1\75\15\3\1\76"+
    "\7\3\56\0\1\77\21\0\1\44\1\4\1\0\31\44"+
    "\1\0\1\100\4\4\1\0\7\4\2\0\1\4\1\0"+
    "\1\44\1\4\1\0\31\44\1\0\1\4\1\101\3\4"+
    "\1\0\7\4\2\0\1\4\1\0\1\44\1\4\1\0"+
    "\31\44\1\0\2\4\1\102\1\103\1\4\1\0\7\4"+
    "\2\0\1\4\1\0\1\44\1\4\1\5\31\44\1\0"+
    "\5\4\1\0\4\4\1\41\2\4\2\5\1\4\1\0"+
    "\1\44\1\4\1\0\31\44\1\104\5\4\1\0\7\4"+
    "\2\0\1\4\1\0\2\44\1\0\31\44\22\0\2\3"+
    "\1\0\2\3\1\105\26\3\22\0\2\3\1\0\13\3"+
    "\1\106\15\3\22\0\2\3\1\0\2\3\1\107\2\3"+
    "\1\110\23\3\22\0\2\3\1\0\2\3\1\111\26\3"+
    "\22\0\2\3\1\0\1\3\1\112\27\3\22\0\2\3"+
    "\1\0\6\3\1\113\22\3\22\0\2\3\1\0\13\3"+
    "\1\114\15\3\22\0\2\3\1\0\1\3\1\115\10\3"+
    "\1\116\16\3\22\0\2\3\1\0\7\3\1\117\21\3"+
    "\22\0\2\3\1\0\6\3\1\120\22\3\22\0\2\3"+
    "\1\0\7\3\1\54\21\3\22\0\2\3\1\0\5\3"+
    "\1\121\4\3\1\122\1\3\1\123\14\3\22\0\2\3"+
    "\1\0\1\11\30\3\22\0\2\3\1\0\22\3\1\124"+
    "\6\3\22\0\2\3\1\0\10\3\1\125\20\3\22\0"+
    "\2\3\1\0\1\3\1\126\27\3\22\0\2\3\1\0"+
    "\5\3\1\127\4\3\1\130\16\3\22\0\2\3\1\0"+
    "\3\3\1\131\25\3\22\0\2\3\1\0\10\3\1\132"+
    "\20\3\22\0\2\3\1\0\2\3\1\133\26\3\22\0"+
    "\2\3\1\0\1\134\30\3\22\0\2\3\1\0\5\3"+
    "\1\62\23\3\22\0\2\3\1\0\4\3\1\135\6\3"+
    "\1\136\15\3\22\0\2\3\1\0\11\3\1\137\17\3"+
    "\22\0\1\140\1\102\1\0\31\140\1\0\2\4\1\141"+
    "\2\4\1\0\7\4\2\142\1\4\1\0\1\143\1\103"+
    "\1\0\31\143\1\0\5\4\1\0\7\4\1\143\1\0"+
    "\1\4\1\0\2\3\1\0\1\144\3\3\1\145\24\3"+
    "\22\0\2\3\1\0\16\3\1\146\12\3\22\0\2\3"+
    "\1\0\6\3\1\147\22\3\22\0\2\3\1\0\3\3"+
    "\1\150\25\3\22\0\2\3\1\0\13\3\1\151\15\3"+
    "\22\0\2\3\1\0\22\3\1\152\6\3\22\0\2\3"+
    "\1\0\10\3\1\54\20\3\22\0\2\3\1\0\30\3"+
    "\1\54\22\0\2\3\1\0\12\3\1\153\16\3\22\0"+
    "\2\3\1\0\1\65\30\3\22\0\2\3\1\0\1\154"+
    "\30\3\22\0\2\3\1\0\12\3\1\155\16\3\22\0"+
    "\2\3\1\0\3\3\1\156\25\3\22\0\2\3\1\0"+
    "\2\3\1\157\4\3\1\155\21\3\22\0\2\3\1\0"+
    "\4\3\1\160\24\3\22\0\2\3\1\0\6\3\1\161"+
    "\22\3\22\0\2\3\1\0\1\162\30\3\22\0\2\3"+
    "\1\0\4\3\1\54\24\3\22\0\2\3\1\0\3\3"+
    "\1\156\4\3\1\163\20\3\22\0\2\3\1\0\2\3"+
    "\1\164\26\3\22\0\2\3\1\0\7\3\1\165\21\3"+
    "\22\0\2\3\1\0\12\3\1\126\16\3\22\0\2\3"+
    "\1\0\4\3\1\166\24\3\22\0\2\3\1\0\1\3"+
    "\1\167\27\3\22\0\2\3\1\0\2\3\1\170\15\3"+
    "\1\171\10\3\22\0\2\3\1\0\1\3\1\172\12\3"+
    "\1\173\14\3\22\0\2\3\1\0\10\3\1\174\20\3"+
    "\22\0\2\140\1\0\31\140\3\0\1\175\12\0\2\142"+
    "\2\0\1\44\1\4\1\0\31\44\1\0\3\4\1\176"+
    "\1\4\1\0\7\4\2\0\1\4\1\0\2\142\1\0"+
    "\31\142\3\0\1\175\12\0\2\142\2\0\2\143\1\0"+
    "\31\143\16\0\1\143\3\0\2\3\1\0\3\3\1\126"+
    "\25\3\22\0\2\3\1\0\1\3\1\177\27\3\22\0"+
    "\2\3\1\0\13\3\1\200\15\3\22\0\2\3\1\0"+
    "\2\3\1\174\26\3\22\0\2\3\1\0\13\3\1\201"+
    "\15\3\22\0\2\3\1\0\1\202\30\3\22\0\2\3"+
    "\1\0\1\203\30\3\22\0\2\3\1\0\2\3\1\157"+
    "\26\3\22\0\2\3\1\0\1\3\1\204\27\3\22\0"+
    "\2\3\1\0\1\54\30\3\22\0\2\3\1\0\1\205"+
    "\30\3\22\0\2\3\1\0\3\3\1\206\25\3\22\0"+
    "\2\3\1\0\10\3\1\207\20\3\22\0\2\3\1\0"+
    "\3\3\1\210\25\3\22\0\2\3\1\0\6\3\1\65"+
    "\22\3\22\0\2\3\1\0\21\3\1\211\7\3\22\0"+
    "\2\3\1\0\6\3\1\212\22\3\22\0\2\3\1\0"+
    "\6\3\1\213\22\3\22\0\2\3\1\0\7\3\1\214"+
    "\21\3\22\0\2\3\1\0\2\3\1\215\26\3\22\0"+
    "\2\3\1\0\1\216\30\3\22\0\2\3\1\0\13\3"+
    "\1\217\15\3\22\0\2\3\1\0\5\3\1\220\23\3"+
    "\22\0\2\3\1\0\6\3\1\221\22\3\22\0\2\3"+
    "\1\0\13\3\1\222\15\3\62\0\1\223\15\0\2\3"+
    "\1\0\5\3\1\224\23\3\22\0\2\3\1\0\1\3"+
    "\1\225\27\3\22\0\2\3\1\0\11\3\1\211\17\3"+
    "\22\0\2\3\1\0\1\3\1\226\27\3\22\0\2\3"+
    "\1\0\1\3\1\227\27\3\22\0\2\3\1\0\6\3"+
    "\1\230\22\3\22\0\2\3\1\0\16\3\1\231\12\3"+
    "\22\0\2\3\1\0\21\3\1\232\7\3\22\0\2\3"+
    "\1\0\14\3\1\62\14\3\22\0\2\3\1\0\13\3"+
    "\1\233\15\3\22\0\2\3\1\0\13\3\1\11\15\3"+
    "\22\0\2\3\1\0\1\3\1\234\27\3\22\0\2\3"+
    "\1\0\7\3\1\235\21\3\22\0\2\3\1\0\4\3"+
    "\1\236\24\3\22\0\2\3\1\0\3\3\1\237\25\3"+
    "\22\0\2\3\1\0\22\3\1\240\6\3\22\0\2\3"+
    "\1\0\1\241\30\3\22\0\2\3\1\0\13\3\1\242"+
    "\15\3\22\0\2\3\1\0\7\3\1\126\21\3\22\0"+
    "\2\3\1\0\5\3\1\126\23\3\22\0\2\3\1\0"+
    "\1\236\30\3\22\0\2\3\1\0\6\3\1\11\22\3"+
    "\22\0\2\3\1\0\7\3\1\155\21\3\22\0\2\3"+
    "\1\0\2\3\1\155\26\3\22\0\2\3\1\0\24\3"+
    "\1\243\4\3\22\0\2\3\1\0\1\244\30\3\22\0"+
    "\2\3\1\0\5\3\1\245\23\3\22\0\2\3\1\0"+
    "\2\3\1\246\26\3\22\0\2\3\1\0\5\3\1\247"+
    "\23\3\22\0\2\3\1\0\1\144\30\3\22\0\2\3"+
    "\1\0\12\3\1\54\16\3\22\0\2\3\1\0\6\3"+
    "\1\236\22\3\22\0\2\3\1\0\13\3\1\221\15\3"+
    "\22\0\2\3\1\0\7\3\1\250\21\3\22\0\2\3"+
    "\1\0\20\3\1\52\10\3\22\0\2\3\1\0\25\3"+
    "\1\251\1\252\1\16\1\3\22\0\2\3\1\0\1\3"+
    "\1\253\27\3\22\0\2\3\1\0\2\3\1\254\26\3"+
    "\22\0\2\3\1\0\16\3\1\126\12\3\22\0\2\3"+
    "\1\0\13\3\1\225\15\3\22\0\2\3\1\0\6\3"+
    "\1\255\22\3\22\0\2\3\1\0\1\3\1\256\27\3"+
    "\22\0\2\3\1\0\1\52\30\3\22\0\2\3\1\0"+
    "\2\3\1\225\26\3\22\0\2\3\1\0\4\3\1\11"+
    "\24\3\22\0\2\3\1\0\7\3\1\224\21\3\22\0"+
    "\2\3\1\0\2\3\1\235\26\3\21\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7268];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\1\11\31\1\1\11\42\1\1\11\4\1\1\11"+
    "\35\1\1\0\32\1\1\0\25\1\1\11\33\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[174];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    public String lexeme;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 152) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Tokens yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 19: 
          { return Masmas;
          }
        case 24: break;
        case 20: 
          { return Menosmenos;
          }
        case 25: break;
        case 5: 
          { return Igual;
          }
        case 26: break;
        case 15: 
          { return Mayorque;
          }
        case 27: break;
        case 8: 
          { return Multiplicacion;
          }
        case 28: break;
        case 6: 
          { return Suma;
          }
        case 29: break;
        case 11: 
          { return Exponencial;
          }
        case 30: break;
        case 16: 
          { return Puntocoma;
          }
        case 31: break;
        case 10: 
          { return Modulo;
          }
        case 32: break;
        case 1: 
          { lexeme=yytext(); return ErrorVariable;
          }
        case 33: break;
        case 14: 
          { return Menorque;
          }
        case 34: break;
        case 22: 
          { return Distintoque;
          }
        case 35: break;
        case 9: 
          { return Division;
          }
        case 36: break;
        case 21: 
          { lexeme=yytext(); return Comentario;
          }
        case 37: break;
        case 13: 
          { return Pcerrar;
          }
        case 38: break;
        case 18: 
          { return Igualque;
          }
        case 39: break;
        case 7: 
          { return Resta;
          }
        case 40: break;
        case 12: 
          { return Pabrir;
          }
        case 41: break;
        case 23: 
          { lexeme=yytext(); return ComentarioG;
          }
        case 42: break;
        case 3: 
          { lexeme=yytext(); return Identificador;
          }
        case 43: break;
        case 2: 
          { return ERROR;
          }
        case 44: break;
        case 4: 
          { /*Ignore*/
          }
        case 45: break;
        case 17: 
          { lexeme=yytext(); return Reservadas;
          }
        case 46: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
