
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Oct 21 15:08:44 CST 2020
//----------------------------------------------------

package principal;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Si = 10;
  public static final int ErrorVariable = 17;
  public static final int Numero = 14;
  public static final int Comentario = 13;
  public static final int DobleP = 19;
  public static final int Devolver = 18;
  public static final int Entero = 2;
  public static final int Boleano = 4;
  public static final int Identificador = 8;
  public static final int ComentarioG = 12;
  public static final int Pcerrar = 7;
  public static final int Pabrir = 6;
  public static final int Sino = 11;
  public static final int Cadena = 3;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int Real = 5;
  public static final int Igual = 9;
  public static final int Error = 15;
  public static final int Principal = 16;
}

