
package principal;


public enum Tokens {
    
    /*------------Asignaciones ------------*/
    GUION,
    ESPACIO,
    //tipoF,
    /*-----------Clase ------------------*/
    IdentificadorClase,
    ErrorIdentificadorClase,
    
    /*------------funcioon ------------------*/
    IdentificadorFuncion,
    ErrorIdentificadorFuncion,
    
    /*-----------Variables------------------*/
    IdentificadorVariable,
    ErrorIdentificadorVariable,
    
    DobleP,
    Linea,
    ComentarioG,
    Comentario,
    ErrorVariable,
    Reservadas,
    Igual,
    Suma,
    Resta,
    Multiplicacion,
    Division,
    Identificador,
    Numero,
    Modulo,
    ERROR,
    Igualque,
    Masmas,
    Menosmenos,
    Menorque,
    Mayorque,
    Puntocoma,
    Distintoque,
   
    
    //----------Palabras reservadas-----------
    Exponencial,
    Pabrir,
    Pcerrar,
    Coma,
    Punto,
    Entero,
    Cadena,
    Real,
    Boleano,
    Si,
    Sino,
    Devolver,
    Entonces,
    Escribir,
    Leer,
    Verdadero,
    Falso,
    And,
    Or,
    Incrementar,
    Decrementar,
    Hacer,
    Mientras,
    Desde,
    Clase,
    Propiedades,
    Metodos,
    Publicas,
    Privado,
    Protegido,
    Instanciar,
    Extiende,
    Incluir,
    Constructor,
    Principal,
    Eliminar,
    Destructor,
    CadenaAEntero,
    CadenaAReal,
    CadenaABoleano,
    Seno,
    Coseno,
    Tangente,
    Logaritmo,
    Raiz,
    Estatico,
    
}
