
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Nov 14 22:37:18 CST 2020
//----------------------------------------------------

package principal;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Si = 11;
  public static final int Clase = 23;
  public static final int ErrorVariable = 18;
  public static final int Numero = 15;
  public static final int Comentario = 14;
  public static final int DobleP = 20;
  public static final int Devolver = 19;
  public static final int Entero = 3;
  public static final int ERROR = 21;
  public static final int Boleano = 5;
  public static final int Identificador = 9;
  public static final int ComentarioG = 13;
  public static final int Pcerrar = 8;
  public static final int T_dato = 24;
  public static final int Pabrir = 7;
  public static final int Sino = 12;
  public static final int Cadena = 4;
  public static final int EOF = 0;
  public static final int Tabulador = 22;
  public static final int Linea = 2;
  public static final int error = 1;
  public static final int Real = 6;
  public static final int Igual = 10;
  public static final int Error = 16;
  public static final int Principal = 17;
}

